# Generated by Django 5.0 on 2024-01-02 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_imagegallery_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
