# Generated by Django 5.0 on 2024-01-04 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_remove_product_phone_url_product_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='phone',
        ),
    ]
