# Generated by Django 5.0 on 2024-01-09 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_remove_product_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
