# Generated by Django 3.2.23 on 2023-12-15 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mynewapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nevtreh',
        ),
    ]
