# Generated by Django 5.0 on 2024-01-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='District',
        ),
    ]
