# Generated by Django 5.0 on 2024-01-16 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0004_rename_street_address_street_address_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Duureg',
        ),
    ]
